services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/app
    networks:
      - task_manager_network

networks:
  task_manager_network:
    external: true
