services:
  mysql:
    image: mysql:latest
    container_name: task_manager_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: task_manager
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./config.sql:/docker-entrypoint-initdb.d/config.sql

volumes:
  mysql_data:
